### ISSUE TITLE
Convert inline styles to css module

### ISSUE THREAD

**Issue by brandonbyr4** [brandonbyr4/vizoo-api#10]
/components ApiBar is looking perfect, but the styles need to be inside a module.

Take all the inline styles and add them to a CSS module.

**Comment by rajiss-ctrl** [comment]
i am a first time contributor. pls , is the project a reactjs ?  i can handle it.

**Comment by rhinoxD** [comment]
!assign

**Comment by ShashwatAgrawal20** [comment]
hey! would like to work on this
